<?php

return [
  'data' => [
    [
      "migration" => "2025_12_10_000001_create_users_table",
      "label" => "Pengguna",
      "icon" => "fas fa-users",
      "labels" => [
        'name' => 'Nama',
        'username' => 'Nama Pengguna',
        'phone' => 'Telepon',
        'email' => 'Email',
        'email_verified_at' => 'Email Diverifikasi Pada',
        'password' => 'Kata Sandi',
        'role' => 'Peran',
        'picture' => 'Foto',
        'status' => 'Status',
        'remember_token' => 'Token Pengingat',
      ],
      "validation" => [
        'name' => 'required|string|max:255',
        'username' => 'nullable|string|max:255',
        'phone' => 'nullable|string|max:255',
        'email' => 'required|string|email|max:255|unique:users,email',
        'email_verified_at' => 'nullable|date',
        'password' => 'nullable|string|max:255',
        'role' => 'required|string|max:255',
        'picture' => 'nullable|string',
        'status' => 'required|string|max:255',
        'remember_token' => 'nullable|string|max:100',
      ],
    ],
    [
      "migration" => "2025_12_10_000002_create_password_reset_tokens_table",
      "label" => "Token Reset Kata Sandi",
      "icon" => "fas fa-key",
      "labels" => [
        'email' => 'Email',
        'token' => 'Token',
      ],
      "validation" => [
        'email' => 'required|string|email|max:255',
        'token' => 'required|string|max:255',
      ],
    ],
    [
      "migration" => "2025_12_10_000003_create_jobs_table",
      "label" => "Pekerjaan (Jobs)",
      "icon" => "fas fa-cogs",
      "labels" => [
        'queue' => 'Antrean',
        'payload' => 'Muatan Data',
        'attempts' => 'Percobaan',
        'reserved_at' => 'Direservasi Pada',
        'available_at' => 'Tersedia Pada',
      ],
      "validation" => [
        'queue' => 'required|string|max:255',
        'payload' => 'required|string',
        'attempts' => 'required|integer',
        'reserved_at' => 'nullable|integer',
        'available_at' => 'required|integer',
      ],
    ],
    [
      "migration" => "2025_12_10_000004_create_failed_jobs_table",
      "label" => "Pekerjaan Gagal",
      "icon" => "fas fa-times-circle",
      "labels" => [
        'uuid' => 'UUID',
        'connection' => 'Koneksi',
        'queue' => 'Antrean',
        'payload' => 'Muatan Data',
        'exception' => 'Pengecualian',
        'failed_at' => 'Gagal Pada',
      ],
      "validation" => [
        'uuid' => 'required|string|max:255|unique:failed_jobs,uuid',
        'connection' => 'required|string',
        'queue' => 'required|string',
        'payload' => 'required|string',
        'exception' => 'required|string',
        'failed_at' => 'required|date',
      ],
    ],
    [
      "migration" => "2025_12_10_000005_create_personal_access_tokens_table",
      "label" => "Token Akses Personal",
      "icon" => "fas fa-id-card",
      "labels" => [
        'tokenable' => 'Tokenable',
        'name' => 'Nama',
        'token' => 'Token',
        'abilities' => 'Kemampuan',
        'last_used_at' => 'Terakhir Digunakan',
        'expires_at' => 'Kadaluarsa Pada',
      ],
      "validation" => [
        'name' => 'required|string|max:255',
        'token' => 'required|string|max:255|unique:personal_access_tokens,token',
        'abilities' => 'nullable|string',
        'last_used_at' => 'nullable|date',
        'expires_at' => 'nullable|date',
      ],
    ],
    [
      "migration" => "2025_12_10_000006_create_categories_table",
      "label" => "Kategori",
      "icon" => "fas fa-tags",
      "labels" => [
        'user_id' => 'ID Pengguna',
        'parent_id' => 'ID Induk',
        'name' => 'Nama',
        'slug' => 'Slug',
        'type' => 'Tipe',
        'thumbnail' => 'Thumbnail',
        'description' => 'Deskripsi',
        'is_thumbnail_icon' => 'Ikon Thumbnail',
        'is_active' => 'Aktif',
        'is_featured' => 'Unggulan',
      ],
      "validation" => [
        'user_id' => 'nullable|integer|exists:users,id',
        'parent_id' => 'nullable|integer|exists:categories,id',
        'name' => 'required|string|max:255',
        'slug' => 'nullable|string|max:255',
        'type' => 'required|string|max:255',
        'thumbnail' => 'nullable|string',
        'description' => 'nullable|string',
        'is_thumbnail_icon' => 'required|boolean',
        'is_active' => 'required|boolean',
        'is_featured' => 'required|boolean',
      ],
    ],
    [
      "migration" => "2025_12_10_000007_create_blog_categories_table",
      "label" => "Kategori Blog",
      "icon" => "fas fa-book",
      "labels" => [
        'user_id' => 'ID Pengguna',
        'name' => 'Nama',
        'slug' => 'Slug',
        'thumbnail' => 'Thumbnail',
        'description' => 'Deskripsi',
        'seo_keyword' => 'Kata Kunci SEO',
        'seo_description' => 'Deskripsi SEO',
        'is_featured' => 'Unggulan',
        'status' => 'Status',
      ],
      "validation" => [
        'user_id' => 'nullable|integer|exists:users,id',
        'name' => 'required|string|max:255',
        'slug' => 'required|string|max:255',
        'thumbnail' => 'nullable|string',
        'description' => 'nullable|string',
        'seo_keyword' => 'nullable|string',
        'seo_description' => 'nullable|string',
        'is_featured' => 'nullable|boolean',
        'status' => 'required|string|max:255',
      ],
    ],
    [
      "migration" => "2025_12_10_000008_create_blogs_table",
      "label" => "Blog",
      "icon" => "fas fa-newspaper",
      "labels" => [
        'category_id' => 'ID Kategori',
        'user_id' => 'ID Pengguna',
        'title' => 'Judul',
        'slug' => 'Slug',
        'thumbnail' => 'Thumbnail',
        'keyword' => 'Kata Kunci',
        'is_slider' => 'Slider',
        'description' => 'Deskripsi',
        'short_description' => 'Deskripsi Singkat',
        'status' => 'Status',
        'published_at' => 'Diterbitkan Pada',
      ],
      "validation" => [
        'category_id' => 'nullable|integer|exists:blog_categories,id',
        'user_id' => 'nullable|integer|exists:users,id',
        'title' => 'required|string|max:255',
        'slug' => 'required|string|max:255',
        'thumbnail' => 'nullable|string',
        'keyword' => 'required|string',
        'is_slider' => 'nullable|boolean',
        'description' => 'nullable|string',
        'short_description' => 'nullable|string',
        'status' => 'required|string|max:255',
        'published_at' => 'nullable|date',
      ],
    ],
    [
      "migration" => "2025_12_10_000009_create_configurations_table",
      "label" => "Konfigurasi",
      "icon" => "fas fa-cog",
      "labels" => [
        'type' => 'Tipe',
        'value' => 'Nilai',
        'status' => 'Status',
        'description' => 'Deskripsi',
      ],
      "validation" => [
        'type' => 'required|string|max:255',
        'value' => 'nullable|string',
        'status' => 'required|string|max:255',
        'description' => 'nullable|string',
      ],
    ],
    [
      "migration" => "2025_12_10_000010_create_activities_table",
      "label" => "Aktivitas",
      "icon" => "fas fa-history",
      "labels" => [
        'user_id' => 'ID Pengguna',
        'ip_address' => 'Alamat IP',
        'menu' => 'Menu',
        'type' => 'Tipe',
      ],
      "validation" => [
        'user_id' => 'required|integer|exists:users,id',
        'ip_address' => 'required|string|max:255',
        'menu' => 'required|string|max:255',
        'type' => 'required|string|max:255',
      ],
    ],
    [
      "migration" => "2025_12_10_000011_create_products_table",
      "label" => "Produk",
      "icon" => "fas fa-box-open",
      "labels" => [
        'user_id' => 'ID Pengguna',
        'category_id' => 'ID Kategori',
        'assigned_user_id' => 'ID Pengguna Ditugaskan',
        'name' => 'Nama',
        'price' => 'Harga',
        'slug' => 'Slug',
        'instruction' => 'Instruksi',
        'description' => 'Deskripsi',
        'keywords' => 'Kata Kunci',
        'meta_description' => 'Deskripsi Meta',
        'thumbnail' => 'Thumbnail',
        'sort_number' => 'Nomor Urut',
        'status' => 'Status',
        'is_featured' => 'Unggulan',
      ],
      "validation" => [
        'user_id' => 'required|integer|exists:users,id',
        'category_id' => 'required|integer|exists:categories,id',
        'assigned_user_id' => 'nullable|integer|exists:users,id',
        'name' => 'required|string|max:255',
        'price' => 'nullable|integer',
        'slug' => 'required|string|max:255|unique:products,slug',
        'instruction' => 'nullable|string',
        'description' => 'nullable|string',
        'keywords' => 'nullable|string',
        'meta_description' => 'nullable|string',
        'thumbnail' => 'nullable|string',
        'sort_number' => 'nullable|integer',
        'status' => 'required|string|max:255',
        'is_featured' => 'required|boolean',
      ],
    ],
    [
      "migration" => "2025_12_10_000012_create_product_details_table",
      "label" => "Detail Produk",
      "icon" => "fas fa-info-circle",
      "labels" => [
        'product_id' => 'ID Produk',
        'name' => 'Nama',
        'slug' => 'Slug',
        'price' => 'Harga',
        'description' => 'Deskripsi',
        'thumbnail' => 'Thumbnail',
        'status' => 'Status',
        'is_custom' => 'Kustom',
      ],
      "validation" => [
        'product_id' => 'required|integer|exists:products,id',
        'name' => 'nullable|string|max:255',
        'slug' => 'nullable|string|max:255',
        'price' => 'required|integer',
        'description' => 'nullable|string',
        'thumbnail' => 'nullable|string',
        'status' => 'required|string|max:255',
        'is_custom' => 'required|boolean',
      ],
    ],
    [
      "migration" => "2025_12_10_000013_create_blog_images_table",
      "label" => "Gambar Blog",
      "icon" => "fas fa-images",
      "labels" => [
        'blog_id' => 'ID Blog',
        'user_id' => 'ID Pengguna',
        'type' => 'Tipe',
        'label' => 'Label',
        'value' => 'Nilai',
      ],
      "validation" => [
        'blog_id' => 'nullable|integer|exists:blogs,id',
        'user_id' => 'nullable|integer|exists:users,id',
        'type' => 'nullable|string|max:255',
        'label' => 'nullable|string|max:255',
        'value' => 'nullable|string',
      ],
    ],
    [
      "migration" => "2025_12_10_000014_create_orders_table",
      "label" => "Pesanan",
      "icon" => "fas fa-shopping-cart",
      "labels" => [
        'user_id' => 'ID Pengguna',
        'product_id' => 'ID Produk',
        'product_detail_id' => 'ID Detail Produk',
        'type' => 'Tipe',
        'order_number' => 'Nomor Pesanan',
        'quantity' => 'Kuantitas',
        'product_price' => 'Harga Produk',
        'price_total' => 'Total Harga',
        'status' => 'Status',
        'status_message' => 'Pesan Status',
        'note' => 'Catatan',
        'detail' => 'Detail',
      ],
      "validation" => [
        'user_id' => 'required|integer|exists:users,id',
        'product_id' => 'nullable|integer|exists:products,id',
        'product_detail_id' => 'nullable|integer|exists:product_details,id',
        'type' => 'required|string|max:255',
        'order_number' => 'required|string|max:255',
        'quantity' => 'required|integer',
        'product_price' => 'required|integer',
        'price_total' => 'required|integer',
        'status' => 'required|string|max:255',
        'status_message' => 'nullable|string|max:255',
        'note' => 'nullable|string',
        'detail' => 'nullable|json',
      ],
    ],
    [
      "migration" => "2025_12_10_000015_create_payments_table",
      "label" => "Pembayaran",
      "icon" => "fas fa-money-bill-wave",
      "labels" => [
        'order_id' => 'ID Pesanan',
        'method' => 'Metode',
        'gross_amount' => 'Jumlah Kotor',
        'net_amount' => 'Jumlah Bersih',
        'fee' => 'Biaya',
        'unix_timestamp' => 'Stempel Waktu Unix',
        'status_code' => 'Kode Status',
        'publisher_order_id' => 'ID Pesanan Penerbit',
        'sp_user_hash' => 'Hash Pengguna SP',
        'issuer_code' => 'Kode Penerbit',
        'settlement_date' => 'Tanggal Penyelesaian',
        'payment_link' => 'Tautan Pembayaran',
        'status' => 'Status',
      ],
      "validation" => [
        'order_id' => 'required|integer|exists:orders,id',
        'method' => 'nullable|string|max:255',
        'gross_amount' => 'required|integer',
        'net_amount' => 'nullable|integer',
        'fee' => 'nullable|integer',
        'unix_timestamp' => 'required|integer',
        'status_code' => 'nullable|string|max:255',
        'publisher_order_id' => 'nullable|string|max:255',
        'sp_user_hash' => 'nullable|string|max:255',
        'issuer_code' => 'nullable|string|max:255',
        'settlement_date' => 'nullable|string|max:255',
        'payment_link' => 'nullable|string|max:255',
        'status' => 'required|string|max:255',
      ],
    ],
    [
      "migration" => "2025_12_10_000016_create_portfolio_categories_table",
      "label" => "Kategori Portofolio",
      "icon" => "fas fa-folder",
      "labels" => [
        'title' => 'Judul',
        'slug' => 'Slug',
        'description' => 'Deskripsi',
        'icon' => 'Ikon',
      ],
      "validation" => [
        'title' => 'required|string|max:255',
        'slug' => 'required|string|max:255',
        'description' => 'nullable|string',
        'icon' => 'nullable|string|max:255',
      ],
    ],
    [
      "migration" => "2025_12_10_000017_create_portfolio_projects_table",
      "label" => "Proyek Portofolio",
      "icon" => "fas fa-project-diagram",
      "labels" => [
        'user_id' => 'ID Pengguna',
        'client_id' => 'ID Klien',
        'category_id' => 'ID Kategori',
        'name' => 'Nama',
        'slug' => 'Slug',
        'price_min' => 'Harga Min',
        'price_max' => 'Harga Max',
        'duration' => 'Durasi',
        'duration_unit' => 'Satuan Durasi',
        'thumbnail' => 'Thumbnail',
        'description' => 'Deskripsi',
        'site_url' => 'URL Situs',
        'is_show_client' => 'Tampilkan Klien',
        'project_date' => 'Tanggal Proyek',
        'project_status' => 'Status Proyek',
        'status' => 'Status',
      ],
      "validation" => [
        'user_id' => 'nullable|integer|exists:users,id',
        'client_id' => 'nullable|integer|exists:clients,id',
        'category_id' => 'nullable|integer|exists:categories,id',
        'name' => 'required|string|max:255',
        'slug' => 'required|string|max:255',
        'price_min' => 'nullable|integer',
        'price_max' => 'nullable|integer',
        'duration' => 'nullable|integer',
        'duration_unit' => 'required|string|max:255',
        'thumbnail' => 'nullable|string',
        'description' => 'nullable|string',
        'site_url' => 'nullable|string',
        'is_show_client' => 'required|boolean',
        'project_date' => 'nullable|date',
        'project_status' => 'required|string|max:255',
        'status' => 'required|string|max:255',
      ],
    ],
    [
      "migration" => "2025_12_10_000018_create_notifications_table",
      "label" => "Notifikasi",
      "icon" => "fas fa-bell",
      "labels" => [
        'user_id' => 'ID Pengguna',
        'order_id' => 'ID Pesanan',
        'title' => 'Judul',
        'body' => 'Isi',
        'type' => 'Tipe',
        'read_at' => 'Dibaca Pada',
      ],
      "validation" => [
        'user_id' => 'required|integer|exists:users,id',
        'order_id' => 'nullable|integer|exists:orders,id',
        'title' => 'nullable|string|max:255',
        'body' => 'required|string',
        'type' => 'nullable|string|max:255',
        'read_at' => 'nullable|date',
      ],
    ],
    [
      "migration" => "2025_12_10_000019_create_images_table",
      "label" => "Gambar",
      "icon" => "fas fa-image",
      "labels" => [
        'product_id' => 'ID Produk',
        'type' => 'Tipe',
        'link' => 'Tautan',
        'file' => 'Berkas',
      ],
      "validation" => [
        'product_id' => 'nullable|integer|exists:products,id',
        'type' => 'required|string|max:255',
        'link' => 'nullable|string',
        'file' => 'nullable|string',
      ],
    ],
    [
      "migration" => "2025_12_10_000020_create_tags_table",
      "label" => "Tag",
      "icon" => "fas fa-tag",
      "labels" => [
        'title' => 'Judul',
        'slug' => 'Slug',
        'is_active' => 'Aktif',
        'is_featured' => 'Unggulan',
      ],
      "validation" => [
        'title' => 'required|string|max:255',
        'slug' => 'required|string|max:255|unique:tags,slug',
        'is_active' => 'required|boolean',
        'is_featured' => 'required|boolean',
      ],
    ],
    [
      "migration" => "2025_12_10_000021_create_product_tags_table",
      "label" => "Tag Produk",
      "icon" => "fas fa-clipboard-list",
      "labels" => [
        'product_id' => 'ID Produk',
        'tag_id' => 'ID Tag',
      ],
      "validation" => [
        'product_id' => 'required|integer|exists:products,id',
        'tag_id' => 'required|integer|exists:tags,id',
      ],
    ],
    [
      "migration" => "2025_12_10_000022_create_pricings_table",
      "label" => "Harga / Pricing",
      "icon" => "fas fa-dollar-sign",
      "labels" => [
        'name' => 'Nama',
        'type' => 'Tipe',
        'unit' => 'Satuan',
        'value' => 'Nilai',
        'applied_to' => 'Diterapkan Pada',
        'status' => 'Status',
      ],
      "validation" => [
        'name' => 'required|string|max:255',
        'type' => 'required|string|max:255',
        'unit' => 'required|string|max:255',
        'value' => 'required|integer',
        'applied_to' => 'required|string|max:255',
        'status' => 'required|string|max:255',
      ],
    ],
    [
      "migration" => "2025_12_10_000023_create_pricing_tags_table",
      "label" => "Tag Harga",
      "icon" => "fas fa-money-check-alt",
      "labels" => [
        'pricing_id' => 'ID Harga',
        'tag_id' => 'ID Tag',
      ],
      "validation" => [
        'pricing_id' => 'required|integer|exists:pricings,id',
        'tag_id' => 'required|integer|exists:tags,id',
      ],
    ],
    [
      "migration" => "2025_12_10_000024_create_work_histories_table",
      "label" => "Riwayat Pekerjaan",
      "icon" => "fas fa-briefcase",
      "labels" => [
        'order_id' => 'ID Pesanan',
        'user_id' => 'ID Pengguna',
        'message' => 'Pesan',
        'type' => 'Tipe',
        'status' => 'Status',
      ],
      "validation" => [
        'order_id' => 'required|integer|exists:orders,id',
        'user_id' => 'nullable|integer|exists:users,id',
        'message' => 'nullable|string',
        'type' => 'required|string|max:255',
        'status' => 'required|string|max:255',
      ],
    ],
    [
      "migration" => "2025_12_10_000025_create_portfolio_images_table",
      "label" => "Gambar Portofolio",
      "icon" => "fas fa-camera-retro",
      "labels" => [
        'user_id' => 'ID Pengguna',
        'portfolio_project_id' => 'ID Proyek Portofolio',
        'type' => 'Tipe',
        'label' => 'Label',
        'value' => 'Nilai',
      ],
      "validation" => [
        'user_id' => 'nullable|integer|exists:users,id',
        'portfolio_project_id' => 'nullable|integer|exists:portfolio_projects,id',
        'type' => 'nullable|string|max:255',
        'label' => 'nullable|string|max:255',
        'value' => 'nullable|string',
      ],
    ],
    [
      "migration" => "2025_12_10_000026_create_profiles_table",
      "label" => "Profil",
      "icon" => "fas fa-user-circle",
      "labels" => [
        'user_id' => 'ID Pengguna',
        'about' => 'Tentang',
        'institute' => 'Institusi',
        'branch' => 'Cabang',
        'job_title' => 'Jabatan',
      ],
      "validation" => [
        'user_id' => 'required|integer|exists:users,id',
        'about' => 'nullable|string',
        'institute' => 'nullable|string|max:255',
        'branch' => 'nullable|string|max:255',
        'job_title' => 'nullable|string|max:255',
      ],
    ],
    [
      "migration" => "2025_12_10_000027_create_banners_table",
      "label" => "Banner",
      "icon" => "fas fa-ad",
      "labels" => [
        'type' => 'Tipe',
        'file' => 'Berkas',
        'title' => 'Judul',
        'description' => 'Deskripsi',
        'is_action_button' => 'Tombol Aksi',
        'action_url' => 'URL Aksi',
        'status' => 'Status',
      ],
      "validation" => [
        'type' => 'required|string|max:255',
        'file' => 'nullable|string',
        'title' => 'nullable|string',
        'description' => 'nullable|string',
        'is_action_button' => 'required|boolean',
        'action_url' => 'nullable|string',
        'status' => 'required|string|max:255',
      ],
    ],
    [
      "migration" => "2025_12_10_000028_create_contacts_table",
      "label" => "Kontak",
      "icon" => "fas fa-address-book",
      "labels" => [
        'name' => 'Nama',
        'email' => 'Email',
        'message' => 'Pesan',
        'is_reply' => 'Sudah Dibalas',
      ],
      "validation" => [
        'name' => 'required|string|max:255',
        'email' => 'required|string|email|max:255',
        'message' => 'required|string',
        'is_reply' => 'required|boolean',
      ],
    ],
    [
      "migration" => "2025_12_10_000029_create_feedbacks_table",
      "label" => "Umpan Balik (Feedback)",
      "icon" => "fas fa-comment-dots",
      "labels" => [
        'order_id' => 'ID Pesanan',
        'product_id' => 'ID Produk',
        'user_id' => 'ID Pengguna',
        'message' => 'Pesan',
        'rating' => 'Peringkat',
        'type' => 'Tipe',
        'status' => 'Status',
      ],
      "validation" => [
        'order_id' => 'nullable|integer|exists:orders,id',
        'product_id' => 'nullable|integer|exists:products,id',
        'user_id' => 'nullable|integer|exists:users,id',
        'message' => 'nullable|string',
        'rating' => 'nullable|integer',
        'type' => 'required|string|max:255',
        'status' => 'required|string|max:255',
      ],
    ],
    [
      "migration" => "2025_12_10_000030_create_attachments_table",
      "label" => "Lampiran",
      "icon" => "fas fa-paperclip",
      "labels" => [
        'work_history_id' => 'ID Riwayat Kerja',
        'type' => 'Tipe',
        'content_type' => 'Tipe Konten',
        'label' => 'Label',
        'value' => 'Nilai',
        'description' => 'Deskripsi',
        'order' => 'Urutan',
      ],
      "validation" => [
        'work_history_id' => 'required|integer|exists:work_histories,id',
        'type' => 'nullable|string|max:255',
        'content_type' => 'nullable|string|max:255',
        'label' => 'nullable|string|max:255',
        'value' => 'nullable|string',
        'description' => 'nullable|string',
        'order' => 'required|integer',
      ],
    ],
    [
      "migration" => "2025_12_10_000031_create_supported_banks_table",
      "label" => "Bank Terdaftar",
      "icon" => "fas fa-university",
      "labels" => [
        'bank_code' => 'Kode Bank',
        'bank_name' => 'Nama Bank',
        'bi_fast' => 'BI Fast',
        'status' => 'Status',
      ],
      "validation" => [
        'bank_code' => 'required|string|max:255|unique:supported_banks,bank_code',
        'bank_name' => 'required|string|max:255',
        'bi_fast' => 'required|boolean',
        'status' => 'required|string|max:255',
      ],
    ],
    [
      "migration" => "2025_12_10_000032_create_banks_table",
      "label" => "Rekening Bank",
      "icon" => "fas fa-money-check",
      "labels" => [
        'supported_bank_id' => 'ID Bank Terdaftar',
        'bank_name' => 'Nama Bank',
        'bank_account' => 'Nomor Rekening',
        'bank_alias' => 'Alias Bank',
        'attachment' => 'Lampiran',
        'is_primary' => 'Utama',
        'status_message' => 'Pesan Status',
        'status' => 'Status',
      ],
      "validation" => [
        'supported_bank_id' => 'nullable|integer|exists:supported_banks,id',
        'bank_name' => 'nullable|string|max:255',
        'bank_account' => 'nullable|string|max:255',
        'bank_alias' => 'nullable|string|max:255',
        'attachment' => 'nullable|string',
        'is_primary' => 'required|boolean',
        'status_message' => 'nullable|string|max:255',
        'status' => 'required|string|max:255',
      ],
    ],
    [
      "migration" => "2025_12_10_000033_create_withdraws_table",
      "label" => "Penarikan Dana (Withdraw)",
      "icon" => "fas fa-hand-holding-usd",
      "labels" => [
        'user_id' => 'ID Pengguna',
        'submited_user_id' => 'ID Pengguna Pengaju',
        'bank_id' => 'ID Bank',
        'transaction_number' => 'Nomor Transaksi',
        'gross_amount' => 'Jumlah Kotor',
        'net_amount' => 'Jumlah Bersih',
        'fee' => 'Biaya',
        'attachment' => 'Lampiran',
        'method' => 'Metode',
        'account_name' => 'Nama Pemilik Rekening',
        'disburse_id' => 'ID Pencairan',
        'reff_number' => 'Nomor Referensi',
        'status' => 'Status',
        'detail' => 'Detail',
        'status_message' => 'Pesan Status',
      ],
      "validation" => [
        'user_id' => 'required|integer|exists:users,id',
        'submited_user_id' => 'nullable|integer|exists:users,id',
        'bank_id' => 'required|integer|exists:banks,id',
        'transaction_number' => 'nullable|string|max:255',
        'gross_amount' => 'required|integer',
        'net_amount' => 'required|integer',
        'fee' => 'required|integer',
        'attachment' => 'nullable|string',
        'method' => 'nullable|string|max:255',
        'account_name' => 'nullable|string|max:255',
        'disburse_id' => 'nullable|string|max:255',
        'reff_number' => 'nullable|string|max:255',
        'status' => 'required|string|max:255',
        'detail' => 'nullable|string',
        'status_message' => 'nullable|string|max:255',
      ],
    ],
    [
      "migration" => "2025_12_10_000034_create_wallets_table",
      "label" => "Dompet (Wallet)",
      "icon" => "fas fa-wallet",
      "labels" => [
        'user_id' => 'ID Pengguna',
        'order_id' => 'ID Pesanan',
        'withdraw_id' => 'ID Penarikan',
        'debit' => 'Debit',
        'credit' => 'Kredit',
      ],
      "validation" => [
        'user_id' => 'required|integer|exists:users,id',
        'order_id' => 'nullable|integer|exists:orders,id',
        'withdraw_id' => 'nullable|integer|exists:withdraws,id',
        'debit' => 'required|integer',
        'credit' => 'required|integer',
      ],
    ],
  ]
];