<?php

declare(strict_types=1);

namespace App\Enums;

use BenSampo\Enum\Enum;

final class ConfigurationType extends Enum
{
  const DUITKU_DISBURSEMENT = 'DUITKU_DISBURSEMENT';
  const FEE_PLATFORM = 'FEE_PLATFORM';
  const FEE_TRANSFER_BANK = 'FEE_TRANSFER_BANK';
  const UNDER_CONSTRUCTION = 'UNDER_CONSTRUCTION';
  const WORK_SUBMIT_TTL = 'WORK_SUBMIT_TTL';
  const FEATURED_MAX_ROW = 'FEATURED_MAX_ROW';
  const WHATSAPP_NUMBER = 'WHATSAPP_NUMBER';
  const EMAIL = 'EMAIL';
  const ADDRESS = 'ADDRESS';
  const CONTENT_ABOUT = 'CONTENT_ABOUT';
  const CONTENT_TERM_CONDITION = 'CONTENT_TERM_CONDITION';
  const CONTENT_PRIVACY_POLICY = 'CONTENT_PRIVACY_POLICY';
  const CONTENT_DISCLAIMER = 'CONTENT_DISCLAIMER';
  const CONTENT_FAQ = 'CONTENT_FAQ';
  const TAGLINE = 'TAGLINE';
}
